service: timetracker
image: teyermann/timetracker

servers:
  web:
    - timetracker.dotsncircles.com
  worker:
    hosts:
      - timetracker.dotsncircles.com
    cmd: bin/rails solid_queue:start

proxy:
  forward_headers: true
  app_port: 3000

registry:
  username: teyermann
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

builder:
  arch: amd64
  cache:
    type: gha
    options: mode=max
    image: app-build-cache

volumes:
  - "/root/docker_storage/timetracker_db/:/rails/storage"

ssh:
  port: 2223
  keys_only: true
